services:
  app:
    restart: unless-stopped
    image: blurrycontour/medbot:app
    build:
      context: '.'
      dockerfile: Dockerfile
      network: host
    # command: "python -m medbot.run"
    environment:
      - MONGODB_STRING=${MONGODB_STRING}
      - ENVIRONMENT=${ENVIRONMENT}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - AI_GATEWAY_API_KEY=${AI_GATEWAY_API_KEY}
      - APPROVED_USERS=${APPROVED_USERS}
      - ADMIN_USER_ID=${ADMIN_USER_ID}
      - LOG_LEVEL=${LOG_LEVEL}
    volumes:
      - /.logs:/repo/.logs
    networks:
      - medbot-network

networks:
  medbot-network:
    driver: bridge
